# Generated by Django 5.2.8 on 2025-11-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('SCRAPE', 'Scrape Website'), ('SUMMARIZE', 'Summarize Text'), ('TRANSLATE', 'Translate Text'), ('EMAIL', 'Send Email'), ('CUSTOM', 'Custom Python Step')], max_length=20)),
                ('order', models.IntegerField()),
                ('input_data', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.pipeline')),
            ],
        ),
    ]
