# Generated by Django 5.2.8 on 2025-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestep',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
    ]
